language: node_js

node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Site Update"
  - git push --force --quiet "https://${token}@github.com/Moocii/Moocii.github.io.git" master:master

branches:
  only:
    - src

cache:
  directories:
    - node_modules
